export interface ResourceLink {
  id: number;
  name: string;
  category: string; // ex: "Universidade", "Repositório"
  url: string;
}

export const links: ResourceLink[] = [
  { id: 1, name: "Universidade de Lisboa", category: "Universidade", url: "https://www.ulisboa.pt/" },
  { id: 2, name: "SciELO", category: "Repositório", url: "https://www.scielo.org/" },
  { id: 3, name: "Google Scholar", category: "Busca", url: "https://scholar.google.com/" },
  { id: 4, name: "JURN", category: "Busca", url: "https://www.jurn.link/" },
  { id: 5, name: "JSTOR (Open Access)", category: "Revista", url: "https://about.jstor.org/oa-and-free/" },
  { id: 6, name: "Oxford Academic Journals", category: "Revista", url: "https://academic.oup.com/journals" },
  { id: 7, name: "Redalyc", category: "Revista", url: "https://www.redalyc.org/" },
  { id: 8, name: "DOAJ", category: "Revista", url: "https://doaj.org/" },
  { id: 9, name: "Análise Social", category: "Revista", url: "http://analisesocial.ics.ul.pt/" },
  { id: 10, name: "Portuguese Journal of Social Science", category: "Revista", url: "http://pjss.iscte-iul.pt/" },
  { id: 11, name: "American Historical Review", category: "Revista", url: "https://academic.oup.com/ahr" },
  { id: 12, name: "Ayer", category: "Revista", url: "https://www.ahistcon.org/revistaayer.html" },
  { id: 13, name: "Cuadernos de Historia Contemporánea", category: "Revista", url: "https://revistas.ucm.es/index.php/CHCO" },
  { id: 14, name: "e-Journal of Portuguese History", category: "Revista", url: "https://ejph.org/" },
  { id: 15, name: "Fragmenta Historica", category: "Revista", url: "https://journals.openedition.org/fragmenta/" },
  { id: 16, name: "Internet Archaeology", category: "Revista", url: "https://intarch.ac.uk/" },
  { id: 17, name: "Ler História", category: "Revista", url: "https://journals.openedition.org/lerhistoria/" },
  { id: 18, name: "Medievalista", category: "Revista", url: "https://medievalista.fcsh.unl.pt/" },
  { id: 19, name: "Past and Present", category: "Revista", url: "https://academic.oup.com/past" },
  { id: 20, name: "Práticas da História", category: "Revista", url: "http://www.praticasdahistoria.pt/pt/" },
  { id: 21, name: "RCAAP", category: "Repositório", url: "https://www.rcaap.pt/" },
  { id: 22, name: "Repositório ULisboa", category: "Repositório", url: "https://repositorio.ul.pt/" },
  { id: 23, name: "Repositório Aberto UP", category: "Repositório", url: "https://repositorio-aberto.up.pt/" },
  { id: 24, name: "RUN - UNL", category: "Repositório", url: "https://run.unl.pt/" },
  { id: 25, name: "Estudo Geral - UC", category: "Repositório", url: "https://estudogeral.sib.uc.pt/" },
  { id: 26, name: "USP - Teses e Dissertações", category: "Teses", url: "https://www.teses.usp.br/" },
  { id: 27, name: "Pantheon - UFRJ", category: "Teses", url: "https://pantheon.ufrj.br/" },
  { id: 28, name: "Repositório UFMG", category: "Teses", url: "https://repositorio.ufmg.br/" },
  { id: 29, name: "Repositório UNICAMP", category: "Teses", url: "https://www.repositorio.unicamp.br/" },
  { id: 30, name: "Repositório UFBA", category: "Teses", url: "https://repositorio.ufba.br/" },
  { id: 31, name: "OATD", category: "Teses", url: "https://oatd.org/" },
  { id: 32, name: "OpenAlex", category: "Pesquisa", url: "https://openalex.org/" },
  { id: 33, name: "AfricArXiv", category: "Preprints", url: "https://www.africarxiv.org/" },
  { id: 34, name: "Project Gutenberg", category: "Livros", url: "https://www.gutenberg.org/" },
  { id: 35, name: "Internet Archive", category: "Livros", url: "https://archive.org/" },
  { id: 36, name: "Open Library", category: "Livros", url: "https://openlibrary.org/" },
  { id: 37, name: "Projecto Adamastor", category: "Livros", url: "https://projectoadamastor.org/base-de-dados-de-livros-digitais/" },
  { id: 38, name: "Biblioteca Digital Camões", category: "Livros", url: "https://cvc.instituto-camoes.pt/conhecer/biblioteca-digital-camoes.html" },
  { id: 39, name: "Biblioteca Nacional Digital (PT)", category: "Livros", url: "https://purl.pt/" },
  { id: 40, name: "Biblioteca Nacional Digital (BR)", category: "Livros", url: "https://bndigital.bn.br/" },
  { id: 41, name: "Portal Domínio Público", category: "Livros", url: "http://www.dominiopublico.gov.br/" },
  { id: 42, name: "UniCV - Biblioteca Digital", category: "Livros", url: "http://rdigital.unicv.edu.cv/" },
  { id: 43, name: "UAN - Biblioteca Digital", category: "Livros", url: "https://www.uan.ao/" },
  { id: 44, name: "Jean Piaget GB - Virtual", category: "Livros", url: "http://guine-bissau.unipiaget.org/index.html" },
  { id: 45, name: "Marxists Internet Archive (MIA)", category: "Arquivos", url: "https://www.marxists.org/" },
  { id: 46, name: "The Anarchist Library", category: "Arquivos", url: "https://theanarchistlibrary.org/" },
  { id: 47, name: "IISH - Social History", category: "Arquivos", url: "https://socialhistory.org/" },
  { id: 48, name: "Jornal A Verdade", category: "Mídias", url: "https://averdade.org/" },
  { id: 49, name: "Brasil de Fato", category: "Mídias", url: "https://www.brasildefato.com.br/" },
  { id: 50, name: "Jacobin Magazine", category: "Mídias", url: "https://jacobin.com/" },
  { id: 51, name: "CounterPunch", category: "Mídias", url: "https://www.counterpunch.org/" },
  { id: 52, name: "Morning Star", category: "Mídias", url: "https://morningstaronline.co.uk/" },
  { id: 53, name: "Le Monde Diplomatique", category: "Mídias", url: "https://mondediplo.com/" },
  { id: 54, name: "MST", category: "Movimento", url: "https://mst.org.br/" },
  { id: 55, name: "Via Campesina", category: "Movimento", url: "https://viacampesina.org/en/" },
  { id: 56, name: "CUT", category: "Organização", url: "https://cut.org.br/" },
  { id: 57, name: "ATTAC", category: "Organização", url: "https://www.attac.org/" },
  { id: 58, name: "PAME", category: "Movimento", url: "https://pamehellas.gr/" },
  { id: 59, name: "Libcom.org", category: "Arquivos", url: "https://libcom.org/" },
  { id: 60, name: "Left Archive", category: "Arquivos", url: "https://www.leftarchive.org/" },
  { id: 61, name: "Solidarity Federation", category: "Organização", url: "https://www.solfed.org.uk/" },
  { id: 62, name: "British Library", category: "Museu", url: "https://explore.bl.uk/" },
  { id: 63, name: "Library of Congress", category: "Museu", url: "https://catalog.loc.gov/" },
  { id: 64, name: "Museu do Louvre", category: "Museu", url: "https://www.louvre.fr/" },
  { id: 65, name: "British Museum", category: "Museu", url: "https://www.britishmuseum.org/" },
  { id: 66, name: "The MET", category: "Museu", url: "https://www.metmuseum.org/" },
  { id: 67, name: "Victoria and Albert Museum", category: "Museu", url: "https://www.vam.ac.uk/" },
  { id: 68, name: "ICOM", category: "Instituição", url: "https://icom.museum/" },
  { id: 69, name: "Património Cultural (PT)", category: "Instituição", url: "https://www.patrimoniocultural.pt/" },
  { id: 70, name: "FCSH - Nova", category: "Universidade", url: "https://www.fcsh.unl.pt/" },
  { id: 71, name: "ISCTE", category: "Universidade", url: "https://www.iscte.pt/" },
  { id: 72, name: "FLUC - Coimbra", category: "Universidade", url: "https://www.uc.pt/fluc/" },
  { id: 73, name: "FLUL - Lisboa", category: "Universidade", url: "https://www.letras.ulisboa.pt/pt/" },
  { id: 74, name: "FLUP - Porto", category: "Universidade", url: "https://sigarra.up.pt/flup/web_page.inicial" },
  { id: 75, name: "IHC", category: "Instituto", url: "https://ihc.fcsh.unl.pt/" },
  { id: 76, name: "CHAM", category: "Instituto", url: "https://cham.fcsh.unl.pt/" },
  { id: 77, name: "ICS - ULisboa", category: "Instituto", url: "https://www.ics.ul.pt/" },
  { id: 78, name: "USP", category: "Universidade", url: "https://www5.usp.br/" },
  { id: 79, name: "UFRJ", category: "Universidade", url: "https://ufrj.br/" },
  { id: 80, name: "UFRGS", category: "Universidade", url: "https://www.ufrgs.br/" },
  { id: 81, name: "UAN (Angola)", category: "Universidade", url: "https://www.uan.ao/" },
  { id: 82, name: "UniCV (Cabo Verde)", category: "Universidade", url: "https://www.unicv.edu.cv/" },
  { id: 83, name: "UEM (Moçambique)", category: "Universidade", url: "https://www.uem.mz/" }
];
